# Generated by Django 3.0.4 on 2020-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='descritpion',
            new_name='description',
        ),
    ]
